export interface Brand {
  id: string; // generated by Firestore
  brandName: string;
  brandRating: number; // default rating, can be updated later
}

/* Brand statistics interface */
export interface BrandStats {
  price: number;
  quality: number;
  nutrition: number;
  sustainability: number;
  overallScore: number;
  productCount: number;
}