/**
 * Firestore fields need to start with a capital letter to stay consistent.
 */
export interface Review {
  Id: string; // generated by Firestore
  CreatedAt: Date;
  ProductId: string; 
  ReviewText?: string;
  Rating: number;
  UserId: string;  
}