/**
 * Firestore fields need to start with a capital letter to stay consistent.
 */
export interface Review {
  id: string; // generated by Firestore
  createdAt: Date;
  productId: string; 
  reviewText?: string;
  rating: number; // 1-5 star rating
  userId: string;
  isAnonymous?: boolean; // whether the review is anonymous
}