/**
 * Firestore fields need to start with a capital letter to stay consistent.
 */
export interface Review {
  Id: string; // generated by Firestore, not rele
  CreatedAt: Date;
  ProductId: string; 
  ReviewText?: string; // Optional review text
  UserId: string;  
}