/**
 * Firestore fields need to start with a capital letter to stay consistent.
 */
export interface Review {
  id: string; // generated by Firestore
  createdAt: Date;
  productId: string; 
  reviewText?: string;
  valueRating: number;
  qualityRating: number;
  averageRating?: number;
  userId: string;
}